### ISSUE TITLE
How can I deploy on Preview or Preprod network 

### ISSUE THREAD

**Issue by ironmask285** [mlabs-haskell/cardano-open-oracle-protocol#90]
I want to initialize COOP on public testnet (preview or preprod). Please help me

**Comment by ross-spencer** [comment]
@ironmask285 how far have you got with the local-cluster?

**Comment by ironmask285** [comment]
yah, We have successfully deployed on the local cluster, and now we intend to test deploy on the public testnet. Can you provide further guidance for us? @ross-spencer 
![image](https://github.com/mlabs-haskell/cardano-open-oracle-protocol/assets/4832192/6cfefc41-dd54-4e83-a057-39b6772ffdc4)

**Comment by ross-spencer** [comment]
Great work! 

This is from our preprod setup, but you should only need to change three things:

1. Run Cardano node 1.35.5
2. Point plutus-chain-index at the node: `plutus-chain-index --socket-path=$CARDANO_NODE_SOCKET_PATH --port=9084 --network-id 1  --db-path /path/to/chain-index.db start-index `
3. Ensure `pabConfig.yaml` is right, it should be in the `resources/` folder in your coop-tutorial folder. And looks as follows, the network ID should be 1 (it may already be so).

```yaml
-- Calling the cli locally or through an ssh connection
cliLocation:   local
chainIndexUrl: "http://localhost:9084"
networkId:     1

-- Directory name of the script and data files
scriptFileDir:      ".local-cluster/scripts"

-- Directory for the signing key file(s)
signingKeyFileDir:  ".wallets"

-- Directory where the encoded transaction files will be saved
txFileDir:          ".local-cluster/txs"

-- | Directory name of metadata files
metadataDir:         ".local-cluster/metadata"

-- Dry run mode will build the tx, but skip the submit step
dryRun:             false
logLevel:           debug
port:               9080
enableTxEndpoint:   true

-- Save some stats during contract run (only transactions execution budgets supported atm)
collectStats: true

-- Save logs from contract execution: pab request logs and contract logs
collectLogs: true
```
